language: node_js
script:
   - npm run test
deploy:
  provider: heroku
  api_key:
     secure: "PxnoBLvacwXbFp4HsGXEKqM8lbeOdMfp1gIsTNDvnrMhI+0u5I7n095yl4vp6bmnFIC9hOslc3RkWuX7iTyCz3zJUveYBhRP1awMYDh6tuGqZFRPoHgalRKIz+JzoIbY7YyqGS/bKVkKB0ReVt1dXkPC+yYqa7C1ep6xiPLnSIJPC6aKIIKd8xsQpSUo7KIJrTEJSQp9e74sUM4q3Usjp+9PjPID+iAhakf+bP3yQXh7az2gQT8JVNG5TDPwarDlwFRDQt+9RFZjRRXR0Gmq42q4ncBBKYIKniqXsXKqq6nAPuBfwrI9JlHfUCWbwZmIQ8OzXVtyOI5sFboYRR2O1z4Hh0falHj/zZQNJQn1rpkKkwibknHBRqL26EURJC6trALtO5LHeqnZCXkN/mjKZOBVvtk69+bXnWZA42+ueu2NeFKkwtwYigB5tQEcGL7UfZoN7VxWPsmFS0iInTFXkMNI8Mm6JqlmEnoaRSZWT9aOov3hXcc6/bNkKhmzZuwO7YolPu3AWrJ06pWuUi7UC+q9PA33OflsuavmZjlzW4lfkGGzKoqHOMBCcHIK9fFf2jU21dB33WFtm2zkBaSJSFTbzzvIWev2OnzsjxScEBabp08I+A8NGFBfMpDKV6bQwzH2JIgSDWOLbZIFGEhQw1ewgWzuDKv7dBiq9p/I2Pk="
     strategy: git