language: node_js
script:
   - npm run test
deploy:
  provider: heroku
  api_key:
     secure: dSpFbjWO9HCd0tsgf1r3bU89I32p82SvgC6mfaTSXRvlQFrkXZMSXs7xkb7GyCGgtDK8uXP8G+A2EUujVfYylggTrok83paq3wtGes+5S1AIrZEBg1YUH77CrBdvbS7Wnk2PG2moFINg8L/kBKNUD9WV7O3xPYK/QlIkd+AiSnTLnls/kdozazX9iPwulIrCi8bazrfjgSlS+aFADIOaAgIoYrozyLrocDnsXwO/JykO0SmM1pFpqOddmNeYhnwdEMee6AM0+1+lLNaZgl+vOIaZwY602ZHgSIVNsBNGOsaU8Zi+dtD+OppKsmhTZtF0fS+fWoZHCINR347biZGYK8QeDKD3YMltKCzkpEoHWsuwYOHc8tcwNQfD0XIkB542AHMl3cJBgdVaVxCQQk94qcNzxpA8RnSTH7KNYQIha0AiHnF/ZLIuhxi6NTHG/NED/7gk+yvftwuWLtBFShS7uWc1lX2MvejLeWnc/mt0VWbWu+Fe31D06578zACQWMnk7I0z9yY+AL3AGYoaG6lczFYWowbvAFzWgvvrZx2lYSDvVTixM949zCG5ekjxIh1DI9GBzmi1f8l442J1WqdtSd9z/SVVBUkv09Ko3vg5mvCS0S9VuXcU0X3qs+r1km78byXtk1roAd9pNOnsvvxg/9RQlAJ3iVzDMAC4sTnq3P4=