language: node_js
addons:
  sonarcloud:
    organization: moser-ss-github
    token:
        secure: Qg2Qdd3dvGnmcuEujDHvrDyYBQTcCEZC+sQ5OBuFc32fIpdA3qk4RIC4z1VDy1GDqLfowytc4gCB/MuUH1VSzi8N1J2Qou/9PHRlzb5nACLGl9i0cO2vAeT+GvyhHsZe3K6IRk6DKOBY+wtvtNQE6p6RAJhklgr5EcVPo0fPJO+U/oeGRb/E/j7htfmFNzQF1AgQ6mQ4miqehrr+dmPSY6VA/OuUNVUe9Sz7tpP2i5bajSCMp3SPcYG3U/HOuNLMpXLPyqBAHGTq18WT8BJb36lOtoqIDVSBfhT9t+HO+BNTvHxC4WWJCULAwVuWgyjagf2JoVrOBqszh9efkBMz7e2g8SwLGuuRGUV8CS3+q9ZKQDT1N7aLa8zUetVcM3AQeEdFwcJf7x3Bk7YgYGbloYxdTRZOb9dbNKNpUhrRcsxNFi4QXsapFxAWLMWVx9KnBJ14Ubd9oE/37xtAGAUuJ86ak1nETRCx8xkgGwlRylc3+WR1QU1INcUoaZemJLkpaHIvDIaLqyJHEu6CMWBS5Df+RPXQdUBCzkQAy6Fmo/lwlgpPdDG6NHmRBv1R0XiQA5OigHE4L1OInr9hSxthXv8CeVB+18AsjIXgiQG2EPkLxLH7zJNf00wSJ2pdIYBsD/rKO+x/tp1iIFRA5o6DkETc9rtQhP8PX3utm4T6ByQ=
script:
- npm run test-coverage
- sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: L7eqPVuiSc6w2C8utGNBnNHnJWeyn89/AZA47hsvhfA5O8DZLr7Ixa2CQxlROelwiT4ixE9NTQXWUhqJCLJt5QHZpaKU0IVcDZRn75SOPk7hZ8zRi4qWpL3WOjSe1EkXujwHmDc95mbViGy5/jC+fypjmsKBy9Akcur5CH+Ges+L6yDFEL4QLDI/Nu/pH+VIjm/Ido6ItY96vgpEwJFkSgOB9mYKxJLg65TYEqlK+BMP9lbDs/UayWH0sWCxqLJcRUcixNgjnswjBwtyYj42ax1BjeFipuUE3OWCdPKEKd1H485W7DwNSr16ZglHVyx9yVr/t1YY9kfH9U+K3M/Lppcan/DTKRU/lpZzhUZxPGVfCGyFYkMmPM4kXlRi7UhE1R+5Tb/p4Hy2tgkLRCCxAsSVhn2LLGJ7YF1HsxaIwwl+It1c4k08suvSxfhxhNf0Vp3SXHPSPd3ODRdj88AauD+UW4EUyTGslfcnE1PXG8zAIRtT3D4+RLxpA+iS3h+w6E36fAZKhHRzyFHWpH3HDRsYl5j63tHIJF5j2++MddqBvH5avADVGyzuorUV8/uhQEIzXQ1BsPVepuYErvH4Mc6xMLKM1e/8N9WbMvkJxgVeS2gB1ig7NtlQuG2nUORxHwokPnOJHLzZv7Vmp+KxlCJo+vxKUEGtITyAWs+q/j8=
  app: protected-gorge-26765
  on:
    repo: Moser-ss/node-chat-app
